# Generated by Django 3.2.9 on 2023-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betUniversity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='bet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='over_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='over_title',
            field=models.CharField(default='Over Title', max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='under_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='under_title',
            field=models.CharField(default='Under Title', max_length=30),
        ),
    ]
